{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Xarray and parallel computing with dask\n",
    "\n",
    "xarray integrates with dask to support parallel computations and streaming computation on datasets that don’t fit into memory.\n",
    "\n",
    "### Outline\n",
    "- reading and writing data\n",
    "- automatic parallelization\n",
    "- dask schedulers and deployments\n",
    "\n",
    "### Tutorial Duriation\n",
    "10 minutes\n",
    "\n",
    "### Going Further\n",
    "\n",
    "- Xarray's Documentation on using dask: http://xarray.pydata.org/en/latest/dask.html\n",
    "- Dask's Documentation: http://dask.pydata.org/en/latest/"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Dask\n",
    "\n",
    "Dask is a flexible parallel computing library for analytic computing.\n",
    "\n",
    "Dask is composed of two components:\n",
    "\n",
    "- Dynamic task scheduling optimized for computation. This is similar to Airflow, Luigi, Celery, or Make, but optimized for interactive computational workloads.\n",
    "- “Big Data” collections like parallel arrays, dataframes, and lists that extend common interfaces like NumPy, Pandas, or Python iterators to larger-than-memory or distributed environments. These parallel collections run on top of the dynamic task schedulers.\n",
    "\n",
    "![](images/collections-schedulers.png)\n",
    "\n",
    "\n",
    "Dask works by constructing \"task graphs\"\n",
    "\n",
    "![](images/transpose.svg)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Reading and Writing data\n",
    "\n",
    "The usual way to create a dataset filled with dask arrays is to load the data from a netCDF file or files. You can do this by supplying a chunks argument to open_dataset() or using the open_mfdataset() function."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "%matplotlib inline\n",
    "\n",
    "import xarray as xr\n",
    "import numpy as np\n",
    "\n",
    "np.warnings.filterwarnings('ignore')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "distributed.utils - ERROR - Existing exports of data: object cannot be re-sized\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/utils.py\", line 646, in log_errors\n",
      "    yield\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/scheduler.py\", line 1336, in add_worker\n",
      "    'worker-setups': self.worker_setups})\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "distributed.core - ERROR - Existing exports of data: object cannot be re-sized\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 340, in handle_comm\n",
      "    result = yield result\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/scheduler.py\", line 1336, in add_worker\n",
      "    'worker-setups': self.worker_setups})\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<table style=\"border: 2px solid white;\">\n",
       "<tr>\n",
       "<td style=\"vertical-align: top; border: 0px solid white\">\n",
       "<h3>Client</h3>\n",
       "<ul>\n",
       "  <li><b>Scheduler: </b>tcp://127.0.0.1:37265\n",
       "  <li><b>Dashboard: </b><a href='http://127.0.0.1:8787/status' target='_blank'>http://127.0.0.1:8787/status</a>\n",
       "</ul>\n",
       "</td>\n",
       "<td style=\"vertical-align: top; border: 0px solid white\">\n",
       "<h3>Cluster</h3>\n",
       "<ul>\n",
       "  <li><b>Workers: </b>8</li>\n",
       "  <li><b>Cores: </b>8</li>\n",
       "  <li><b>Memory: </b>31.63 GB</li>\n",
       "</ul>\n",
       "</td>\n",
       "</tr>\n",
       "</table>"
      ],
      "text/plain": [
       "<Client: scheduler='tcp://127.0.0.1:37265' processes=8 cores=8>"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fead48c5e10> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc791438> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc77e438> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc73d400> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc77ee48> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc7352b0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc77e5c0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc6c3240> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc757128> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc77e5f8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc7086d8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc6e0320> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc6a9b00> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc698668> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc7912e8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc5ffdd8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc659080> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc6235c0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc6d06a0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc6269b0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc5cb630> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc577c50> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc626f28> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc77ebe0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc4f8b00> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc4f9ba8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc561550> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc7a5c50> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc526a90> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "distributed.batched - ERROR - Error in batched write\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/batched.py\", line 94, in _background_send\n",
      "    on_error='raise')\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc561860> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc542128> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc50de48> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc46f240> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc4bb0f0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc4a0be0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc4a0b38> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc51eda0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc459e10> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc459358> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc434ba8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7feabc4229e8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1063, in run\n",
      "    yielded = self.gen.throw(*exc_info)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/core.py\", line 351, in handle_comm\n",
      "    yield comm.write(result, serializers=serializers)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1055, in run\n",
      "    value = future.result()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py\", line 238, in result\n",
      "    raise_exc_info(self._exc_info)\n",
      "  File \"<string>\", line 4, in raise_exc_info\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py\", line 229, in write\n",
      "    stream.write(b)\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 406, in write\n",
      "    self._handle_write()\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/tornado/iostream.py\", line 872, in _handle_write\n",
      "    del self._write_buffer[:self._write_buffer_pos]\n",
      "BufferError: Existing exports of data: object cannot be re-sized\n"
     ]
    }
   ],
   "source": [
    "# use dask's distributed scheduler for now\n",
    "# (see the last section of this notebook for more details)\n",
    "from distributed import Client, progress\n",
    "client = Client()\n",
    "client"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "ds = xr.open_dataset('./data/rasm.nc', chunks={'time': 10})  # this actually loads data using xr.open_dataset\n",
    "ds"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# xarray is now using dask arrays under the hood\n",
    "ds['Tair'].data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "## Xarray operations using dask are now lazy\n",
    "t_range = (ds['Tair'].resample(time='AS').max('time') -\n",
    "           ds['Tair'].resample(time='AS').min('time')).mean('time')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "t_range.data.visualize()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "results = t_range.persist()\n",
    "progress(results)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "results"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Automatic parallelization\n",
    "\n",
    "Almost all of xarray’s built-in operations work on dask arrays. If you want to use a function that isn’t wrapped by xarray, one option is to extract dask arrays from xarray objects (.data) and use dask directly.\n",
    "\n",
    "Another option is to use xarray’s apply_ufunc(), which can automate embarrassingly parallel “map” type operations where a functions written for processing NumPy arrays should be repeatedly applied to xarray objects containing dask arrays. It works similarly to `dask.array.map_blocks()` and `dask.array.atop()`, but without requiring an intermediate layer of abstraction."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import bottleneck\n",
    "\n",
    "def covariance_gufunc(x, y):\n",
    "    return ((x - x.mean(axis=-1, keepdims=True))\n",
    "            * (y - y.mean(axis=-1, keepdims=True))).mean(axis=-1)\n",
    "\n",
    "def pearson_correlation_gufunc(x, y):\n",
    "    return covariance_gufunc(x, y) / (x.std(axis=-1) * y.std(axis=-1))\n",
    "\n",
    "def spearman_correlation_gufunc(x, y):\n",
    "    x_ranks = bottleneck.rankdata(x, axis=-1)\n",
    "    y_ranks = bottleneck.rankdata(y, axis=-1)\n",
    "    return pearson_correlation_gufunc(x_ranks, y_ranks)\n",
    "\n",
    "def spearman_correlation(x, y, dim):\n",
    "    return xr.apply_ufunc(\n",
    "        spearman_correlation_gufunc, x, y,\n",
    "        input_core_dims=[[dim], [dim]],\n",
    "        dask='parallelized',\n",
    "        output_dtypes=[float])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "ds['Tair'].roll(time=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "ds = ds.chunk({'x': 25, 'y': 25, 'time': -1})  # rechunk this dataset\n",
    "\n",
    "# create some toy data using our dataset\n",
    "x = ds['Tair']\n",
    "y = ds['Tair'].roll(time=1)  # lag the air temp data by one month\n",
    "y['time'] = x['time']  # reset the index \n",
    "\n",
    "\n",
    "# calculate the spearman correlation\n",
    "corr = spearman_correlation(x, y, 'time')\n",
    "corr = corr.where(corr < 1)  # make sure nans are masked properly\n",
    "corr"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "corr.plot()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## dask schedulers and deployments\n",
    "\n",
    "Dask provides 4 different mechanisms for executing dask task graphs.\n",
    "\n",
    "- `dask.threaded.get`: a scheduler backed by a thread pool\n",
    "- `dask.multiprocessing.get`: a scheduler backed by a process pool\n",
    "- `dask.get`: a synchronous scheduler, good for debugging\n",
    "- `distributed.Client.get`: a distributed scheduler for executing graphs"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import dask.multiprocessing\n",
    "dask.config.set(scheduler='processes')  # overwrite default with multiprocessing scheduler\n",
    "\n",
    "# or\n",
    "\n",
    "from distributed import Client\n",
    "client = Client()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Lots more! \n",
    "\n",
    "- Setting up dask: http://dask.pydata.org/en/latest/setup.html"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
